name: CI

on: 
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
      run: |
        npm ci
        npm run test,
        npm run build.