name: CI

on: 
  pull_request:
    branches: [main]

jobs:
  unit-test: 
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Deps
        run: npm ci
      - name: Unit Tests  
        run: npm run test
      - name: Build 
        run: npm run build